remote_theme: just-the-docs/just-the-docs
title: আমার আর্কিটেকচার নোটবুক
search_enabled: true

# থিমের ভেতরের ফাঁকা জায়গা বন্ধ করার জন্য (W3Schools Style)
just_the_docs:
  content_max_width: "100%"

sass:
  style: :compressed
